### ISSUE TITLE
Make this a CommonJS module?

### ISSUE THREAD

**Issue by hansemannn** [m1ga/hl.bigimages#1]
https://github.com/m1ga/hl.bigimages/blob/2656dcc3185e5f70a84a523240827ebe6d322acb/app/controllers/index.js#L4

**Comment by m1ga** [comment]
sure!
```
var bigimage = require("/bigimage");
bigimage.setImage(f.nativePath);
$.index.add(bigimage.getView());
```
The custom methods (e.g. setMinimumScaleType) are not working right now. Will fix those soon
